import type { Antenna, AntennaKey } from '../store/useStationStore';

/**
 * The antenna definition file the engine reads, built on the device.
 *
 * VOACAP names an antenna by a path and reads its parameters from that file,
 * so an antenna the operator can change has to exist as a file. The server
 * writes one into the tree it owns; here it goes into the cache directory the
 * native module offers, and the engine is pointed at that directory with the
 * coefficients still coming from inside the library.
 *
 * The text is generated by the same rules as `server/src/antenna.ts` — the
 * card layout, the negative-means-wavelengths convention, and the deliberate
 * difference between the monopole's parameter order and the dipole's. A
 * second set of rules would mean the same station predicted two ways.
 *
 * Lengths and heights are metres, or wavelengths when negative. Element length
 * is -0.5 throughout: a half wave at whatever frequency is being predicted,
 * which models the resonant antenna an operator actually has on each band.
 */

/** The card's fields are fixed width, so every number is right-aligned. */
const field = (value: string, width: number) => value.padStart(width);
const decimals = (value: number, places: number, width: number) =>
  field(value.toFixed(places), width);

/**
 * Ground under the antenna: relative permittivity and conductivity in
 * mhos per metre.
 *
 * The distributed samples all use 4 and 0.001, which is average ground,
 * and the app does not ask an operator to survey their garden. Holding
 * them fixed also keeps the comparison between two antennas about the
 * antennas.
 */
const DIELECTRIC = 4;
const CONDUCTIVITY = 0.001;

/**
 * The frequency the file's own parameters are quoted against. Only
 * parameters given in wavelengths read it, and the height here is in
 * metres, so it changes nothing; it is written because the format has
 * the slot.
 */
const DESIGN_MHZ = 10;

/**
 * One numbered parameter line. The reader takes the value from the fixed
 * columns at the front; the bracketed number and the name after it are
 * for a human opening the file.
 */
const param = (value: string, index: number, name: string) =>
  `${value}  [${field(String(index), 2)}] ${name}`;

/**
 * The parameters after the five every family shares.
 *
 * Read carefully rather than copied between families: for the monopole
 * parameter 6 is its height and parameter 7 is a gain, where the dipole
 * has length then height. Reading one across from the other would give a
 * vertical whose height was whatever gain figure happened to be set.
 */
function tail(antenna: Antenna): readonly string[] {
  const height = decimals(antenna.heightM, 2, 6);
  switch (antenna.type) {
    case 'dipole':
      return [
        param('  -.50', 6, 'Antenna Length:'),
        param(height, 7, 'Antenna Height:'),
        param('   0.0', 8, 'Gain ab dipole:'),
      ];
    case 'yagi':
      return [
        param('  -.50', 6, 'Antenna Length:'),
        param(height, 7, 'Antenna Height:'),
        param(decimals(antenna.gainDbd, 1, 6), 8, 'Gain ab dipole:'),
      ];
    case 'vertical':
      return [
        param(height, 6, 'Antenna Height:'),
        param('   0.0', 7, 'Gain ab dipole:'),
      ];
    case 'invertedL':
      // Its two parameters are the horizontal run and the vertical drop.
      // An amateur inverted L is usually about a quarter wave of wire in
      // total, so the run is taken as equal to the height rather than
      // asked for separately.
      return [
        param(height, 6, 'Antenna Length:'),
        param(height, 7, 'Antenna Height:'),
      ];
    case 'isotropic':
      return [];
  }
}

const TITLES: Record<AntennaKey, string> = {
  isotropic: 'isotrope',
  dipole: 'dipole',
  vertical: 'vertical',
  yagi: 'yagi',
  invertedL: 'inverted L',
};

function definition(antenna: Antenna): string {
  // Never written for an isotropic station: it names no file at all,
  // which is what the engine already defaults to.
  if (antenna.type === 'isotropic') return '';

  const params = [
    param('  0.00', 1, 'Max Gain dBi..:'),
    param(field(String(TYPE[antenna.type]), 6), 2, 'Antenna Type..:'),
    param(field(String(DIELECTRIC), 6), 3, 'Dielectric....:'),
    param(decimals(CONDUCTIVITY, 5, 6), 4, 'Conductivity..:'),
    param(decimals(DESIGN_MHZ, 3, 6), 5, 'Operating Freq:'),
    ...tail(antenna),
  ];

  // The count on the second line is what the reader trusts: it stops
  // there, so a wrong one drops the parameters after it, the height
  // among them.
  return [
    `HFcast ${TITLES[antenna.type]} ${antenna.heightM} m`,
    `${field(String(params.length), 2)}    ${params.length} parameters`,
    ...params,
    '',
  ].join('\n');
}

const TYPE: Record<AntennaKey, number> = {
  isotropic: 0,
  vertical: 22,
  dipole: 23,
  yagi: 24,
  invertedL: 28,
};

/**
 * Where the file goes, relative to the scratch directory.
 *
 * The card holds 21 columns for the whole path, so the name is built from the
 * parameters rather than from a hash: `antennas/` is stripped by the engine,
 * which leaves `hfcast/` plus the name to fit inside that. The parameters are
 * rounded into the name, so two stations with the same antenna share a file
 * and a station that changes one gets a new one.
 */
const SHORT: Record<AntennaKey, string> = {
  isotropic: 'i',
  dipole: 'd',
  vertical: 'v',
  invertedL: 'l',
  yagi: 'y',
};

export function antennaFileName(antenna: Antenna): string {
  const height = Math.round(antenna.heightM);
  const gain = antenna.type === 'yagi' ? Math.round(antenna.gainDbd) : 0;
  return `hfcast/${SHORT[antenna.type]}${height}g${gain}.voa`;
}

/** What the engine is given: a path under `antennas/`, and where to write it. */
export interface AntennaOnDisk {
  /** The name on the card, as the engine will join it after `antennas/`. */
  file: string;
  /** Where to write it, relative to the scratch directory. */
  path: string;
  text: string;
}

/**
 * The file for this antenna, or null for an isotropic station.
 *
 * Null rather than a file of zeroes: an isotropic station names no antenna at
 * all, which is what the engine already defaults to, and writing a file for it
 * would be describing an assumption as a measurement.
 */
export function antennaOnDisk(antenna: Antenna): AntennaOnDisk | null {
  if (antenna.type === 'isotropic') return null;
  const file = antennaFileName(antenna);
  return {
    file,
    path: `antennas/${file}`,
    text: definition(antenna),
  };
}
