import table from '../assets/licences.json' with { type: 'json' };

/**
 * Who made what this app is built from.
 *
 * Some of this is a courtesy and some is an obligation, and the file does not
 * distinguish them in how it reads — an operator does not care which is which.
 * The obligations, so they are not lost: the SIL Open Font License requires its
 * notice and text to travel with IBM Plex; Apache-2.0 asks the same of the app's
 * own licence; and NTIA/ITS asks that VOACAP be credited and that nothing imply
 * a US Government endorsement, which is what `DISCLAIMER` is for.
 *
 * `id` is a translation key, not a display string: the description of what each
 * credit provides is translated, while the names are proper nouns and are not.
 */
export interface Credit {
  /** Key under `about.credit.` in the locale files. */
  readonly id: string;
  /** The people or body responsible. Not translated. */
  readonly who: string;
  /** Licence or status, as they state it. Not translated. */
  readonly terms: string;
}

export const CREDITS: readonly Credit[] = [
  {
    id: 'voacap',
    who: 'NTIA/ITS, maintained by Greg Hand',
    terms: 'US Government work, not subject to copyright protection in the US',
  },
  {
    id: 'voacapl',
    who: 'J.A. Watson',
    terms: 'CC0',
  },
  {
    id: 'coefficients',
    who: 'CCIR Report 340 and URSI, published by ITU-R',
    terms: 'published for implementers free from copyright assertions',
  },
  {
    id: 'cities',
    who: 'NTIA/ITS, from the VOACAP distribution',
    terms: 'US Government work, not subject to copyright protection in the US',
  },
  {
    id: 'naturalEarth',
    who: 'Natural Earth',
    terms: 'public domain',
  },
  {
    id: 'noaa',
    who: 'NOAA Space Weather Prediction Center',
    terms: 'US Government work, not subject to copyright protection in the US',
  },
  {
    id: 'giro',
    who: 'UMass Lowell Global Ionosphere Radio Observatory',
    terms: 'used with attribution',
  },
  {
    id: 'openMeteo',
    who: 'Open-Meteo',
    terms: 'CC BY 4.0',
  },
  {
    id: 'plex',
    who: 'IBM',
    terms: 'SIL Open Font License 1.1',
  },
];

/**
 * The no-endorsement wording NTIA/ITS asks redistributors to carry.
 *
 * Not translated, and deliberately so: it is a disclaimer about a specific
 * body's position, and a paraphrase in another language would be this project
 * speaking for them.
 */
export const DISCLAIMER =
  'VOACAP was developed by the Institute for Telecommunication Sciences, '
  + 'NTIA, US Department of Commerce. Neither NTIA/ITS nor NOAA endorses '
  + 'HFcast, and neither is responsible for anything it reports. Predictions '
  + 'are climatology with a probability attached, not a guarantee of contact.';

interface LicenceTable {
  licences: readonly { name: string; covers: string; text: string; }[];
}

/** The full licence texts, generated by `tools/build-licences.ts`. */
export const LICENCES = (table as unknown as LicenceTable).licences;
