import table from '../assets/licences.json' with { type: 'json' };

/**
 * Who made what this app is built from.
 *
 * Some of this is a courtesy and some is an obligation, and the file does not
 * distinguish them in how it reads — an operator does not care which is which.
 * The obligations, so they are not lost: the SIL Open Font License requires its
 * notice and text to travel with IBM Plex; Apache-2.0 asks the same of the app's
 * own licence; and NTIA/ITS asks that VOACAP be credited and that nothing imply
 * a US Government endorsement, which is what `DISCLAIMER` is for.
 *
 * `id` is a translation key, not a display string: the description of what each
 * credit provides is translated, while the names are proper nouns and are not.
 */
export interface Credit {
  /** Key under `about.credit.` in the locale files. */
  readonly id: string;
  /** The people or body responsible. Not translated. */
  readonly who: string;
  /** Licence or status, as they state it. Not translated. */
  readonly terms: string;
  /** Where the work itself lives. Shown so a credit can be followed up. */
  readonly url: string;
  /**
   * The licence's own text, where it is published rather than carried.
   *
   * CC BY 4.0 asks for "a URI or hyperlink to the license" as part of the
   * attribution itself, so for Open-Meteo this is an obligation and not a
   * convenience. The licences the app carries in full — see `LICENCES` — do
   * not need one.
   */
  readonly termsUrl?: string;
}

export const CREDITS: readonly Credit[] = [
  {
    id: 'voacap',
    who: 'NTIA/ITS, maintained by Greg Hand',
    terms: 'US Government work, not subject to copyright protection in the US',
    url: 'https://its.ntia.gov/',
  },
  {
    id: 'voacapl',
    who: 'J.A. Watson',
    terms: 'CC0',
    url: 'https://github.com/jawatson/voacapl',
    termsUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  },
  {
    id: 'coefficients',
    who: 'CCIR Reports 322 and 340, published by ITU-R',
    terms: 'published for implementers free from copyright assertions',
    url: 'https://github.com/ITU-R-Study-Group-3/ITU-R-HF',
  },
  {
    id: 'cities',
    who: 'NTIA/ITS, from the VOACAP distribution',
    terms: 'US Government work, not subject to copyright protection in the US',
    url: 'https://its.ntia.gov/',
  },
  {
    id: 'naturalEarth',
    who: 'Natural Earth',
    terms: 'public domain',
    url: 'https://www.naturalearthdata.com/',
  },
  {
    id: 'noaa',
    who: 'NOAA Space Weather Prediction Center',
    terms: 'US Government work, not subject to copyright protection in the US',
    url: 'https://www.swpc.noaa.gov/',
  },
  {
    id: 'giro',
    who: 'UMass Lowell Global Ionosphere Radio Observatory',
    terms: 'used with attribution',
    url: 'https://giro.uml.edu/',
  },
  {
    id: 'openMeteo',
    who: 'Open-Meteo',
    terms: 'CC BY 4.0',
    url: 'https://open-meteo.com/',
    termsUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    id: 'aurora',
    who: 'NASA / Samantha Cristoforetti, ESA',
    terms: 'public domain',
    url:
      'https://commons.wikimedia.org/wiki/File:ISS-42_Aurora_borealis_over_North_Atlantic_Ocean.jpg',
  },
  {
    id: 'plex',
    who: 'IBM',
    terms: 'SIL Open Font License 1.1',
    url: 'https://github.com/IBM/plex',
  },
];

/**
 * The no-endorsement wording NTIA/ITS asks redistributors to carry.
 *
 * Not translated, and deliberately so: it is a disclaimer about a specific
 * body's position, and a paraphrase in another language would be this project
 * speaking for them.
 */
export const DISCLAIMER =
  'VOACAP was developed by the Institute for Telecommunication Sciences, '
  + 'NTIA, US Department of Commerce. Neither NTIA/ITS nor NOAA endorses '
  + 'HFcast, and neither is responsible for anything it reports. Predictions '
  + 'are climatology with a probability attached, not a guarantee of contact.';

interface LicenceTable {
  licences: readonly { name: string; covers: string; text: string; }[];
}

/** The full licence texts, generated by `tools/build-licences.ts`. */
export const LICENCES = (table as unknown as LicenceTable).licences;
