import table from '../assets/licences.json' with { type: 'json' };

/**
 * Who made what this app is built from.
 *
 * Some of this is a courtesy and some is an obligation, and the file does not
 * distinguish them in how it reads — an operator does not care which is which.
 * The obligations, so they are not lost: the SIL Open Font License requires its
 * notice and text to travel with IBM Plex; Apache-2.0 asks the same of the app's
 * own licence; and NTIA/ITS asks that VOACAP be credited and that nothing imply
 * a US Government endorsement, which is what the VOACAP credit's `notice`
 * carries.
 *
 * `id` is a translation key, not a display string: the description of what each
 * credit provides is translated, while the names are proper nouns and are not.
 */
export interface Credit {
  /** Key under `about.credit.` in the locale files. */
  readonly id: string;
  /** The people or body responsible. Not translated. */
  readonly who: string;
  /**
   * The licence, where there is one to name. Not translated.
   *
   * Set only where the licence puts a condition on the reader. A bare
   * status ("public domain", "US Government work") is left off: it reads
   * as a note to a developer rather than as a credit (user, 2026-08-20).
   */
  readonly terms?: string;
  /** Where the work itself lives. Shown so a credit can be followed up. */
  readonly url: string;
  /**
   * The licence's own text, where it is published rather than carried.
   *
   * CC BY 4.0 asks for "a URI or hyperlink to the license" as part of the
   * attribution itself, so for Open-Meteo this is an obligation and not a
   * convenience. The licences the app carries in full — see `LICENCES` — do
   * not need one.
   */
  readonly termsUrl?: string;
  /**
   * A statement this credit is obliged to carry, shown under it.
   *
   * English in every language, deliberately: it is a specific body's own
   * statement of its position, and translating it would be this app
   * speaking on their behalf.
   */
  readonly notice?: string;
}

export const CREDITS: readonly Credit[] = [
  {
    id: 'voacap',
    who:
      'Institute for Telecommunication Sciences (NTIA/ITS), maintained by Greg Hand',
    url: 'https://its.ntia.gov/',
    notice:
      'Neither NTIA/ITS nor NOAA endorses HFcast, and neither is responsible '
      + 'for what it reports.',
  },
  {
    id: 'voacapl',
    who: 'J.A. Watson',
    terms: 'CC0',
    url: 'https://github.com/jawatson/voacapl',
    termsUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
  },
  {
    id: 'coefficients',
    who: 'CCIR Reports 322 and 340, published by ITU-R',
    url: 'https://github.com/ITU-R-Study-Group-3/ITU-R-HF',
  },
  {
    id: 'cities',
    who: 'NTIA/ITS, from the VOACAP distribution',
    url: 'https://its.ntia.gov/',
  },
  {
    id: 'naturalEarth',
    who: 'Natural Earth',
    url: 'https://www.naturalearthdata.com/',
  },
  {
    id: 'noaa',
    who: 'NOAA Space Weather Prediction Center',
    url: 'https://www.swpc.noaa.gov/',
  },
  {
    id: 'giro',
    who: 'UMass Lowell Global Ionosphere Radio Observatory',
    url: 'https://giro.uml.edu/',
  },
  {
    id: 'openMeteo',
    who: 'Open-Meteo',
    terms: 'CC BY 4.0',
    url: 'https://open-meteo.com/',
    termsUrl: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    id: 'plex',
    who: 'IBM',
    terms: 'SIL Open Font License 1.1',
    url: 'https://github.com/IBM/plex',
  },
];

interface LicenceTable {
  licences: readonly { name: string; covers: string; text: string; }[];
}

/** The full licence texts, generated by `tools/build-licences.ts`. */
export const LICENCES = (table as unknown as LicenceTable).licences;
